# Change these first
owner: Jeremias85 # Your GitHub organization or username, where this repository lives
repo: monitor-web # The name of this repository

sites:
  - name: USW Gestión
    url: https://uswgestion.com
  - name: Portal institucional Concejo Deliberante de Ushuaia
    url: https://concejoushuaia.gob.ar
    ##__dangerous__insecure: true
  - name: CMS Concejo Deliberante de Ushuaia
    url: https://concejoushuaia.directus.app
  - name: App legislativa Concejo Deliberante de Ushuaia
    url: https://legislacion.concejoushuaia.gob.ar
    #__dangerous__insecure: true
  - name: App IdM Concejo Deliberante de Ushuaia
    url: https://administracion.concejoushuaia.gob.ar
    #__dangerous__insecure: true
  - name: App administrativa Concejo Deliberante de Ushuaia
    url: https://concejoushuaia.ar
  - name: Portal institucional Escuela Técnica Valentín Virasoro
    url: https://evirasoro.edu.ar
  - name: CMS Escuela Técnica Valentín Virasoro
    url: https://cms.evirasoro.edu.ar
  - name: Moodle Escuela Técnica Valentín Virasoro
    url: https://moodle.evirasoro.edu.ar
  - name: Micrositio Estudiantina Goya 2023
    url: https://estudiantina.evirasoro.edu.ar   
  - name: Página web Hostería Valle Frío Ushuaia
    url: https://vallefrioushuaia.com/
  - name: CMS Municipalidad Santa Lucía Corrientes  
    url: https://cms.santaluciacorrientes.ar
  - name: Portal de prueba municipalidad Santa Lucía Corrientes
    url: http://santaluciacorrientes.ar
    __dangerous__insecure: true
  - name: Página web Canal Web
    url: http://canalweb.com.ar
    __dangerous__insecure: true
    
status-website:
  baseUrl: /monitor-web # where "repo" is your repository name
  name: Status Website
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  introTitle: "Monitor de status de apps y páginas web administradas por **USW Gestión**."
  introMessage: Página de status con datos en **tiempo real**
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
